project:
  type: website
  output-dir: docs

website:
  title: "Web"
  navbar:
    left:
      - href: index.qmd
        text: sanches23rx
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



